# -*- coding: utf-8 -*-
"""Writer script for table_processor.py"""
import os

DOLLAR = chr(36)
BACKSLASH = chr(92)
ZWNJ = chr(0x200C)
NL = chr(10)
Q = chr(39)  # single quote
DQ = chr(34) # double quote

# Build regex patterns as Python source strings safely
# For patterns like \begin, \end, \multicolumn etc.

lines = []

def W(line=""):
    lines.append(line)

W("# -*- coding: utf-8-sig -*-")
W('r"""Table processor for FormatForge.')
W("")
W(f"{ZWNJ.join(['پردازشگر', 'جدول'])} برای FormatForge.")
W('Converts LaTeX and HTML tables to MDX-compatible output.')
W('"""')
W("from __future__ import annotations")
W("")
W("import re")
W("import logging")
W("from typing import List, Optional, Tuple")
W("")
W("from .table_models import TableModel, TableCell, CellStyle")
W("")
W("")
W("logger = logging.getLogger(__name__)")
W("")
W("")
W("# ── Regex patterns built safely ──")
W(f"RE_LATEX_TABLE_ENV = re.compile(")
W(f"    r'{BACKSLASH}{BACKSLASH}begin{chr(123)}(tabular|tabularx|longtable|sidewaystable){chr(125)}'")
W(f"    r'(.*?)'")
W(f"    r'{BACKSLASH}{BACKSLASH}end{chr(123)}{BACKSLASH}1{chr(125)}',")
W(f"    re.DOTALL,")
W(f")")
W(f"RE_COL_SPEC = re.compile(r'{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}')")
W(f"RE_MULTICOLUMN = re.compile(")
W(f"    r'{BACKSLASH}{BACKSLASH}multicolumn{chr(123)}({BACKSLASH}d+){chr(125)}{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}'")
W(f")")
W(f"RE_MULTIROW = re.compile(")
W(f"    r'{BACKSLASH}{BACKSLASH}multirow{chr(123)}({BACKSLASH}d+){chr(125)}{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}'")
W(f")")
W(f"RE_ROWCOLORS = re.compile(")
W(f"    r'{BACKSLASH}{BACKSLASH}rowcolors{chr(123)}({BACKSLASH}d+){chr(125)}{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}'")
W(f")")
W(f"RE_CAPTION = re.compile(r'{BACKSLASH}{BACKSLASH}caption{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}')")
W(f"RE_LABEL = re.compile(r'{BACKSLASH}{BACKSLASH}label{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}')")
W(f"RE_CELLCOLOR = re.compile(r'{BACKSLASH}{BACKSLASH}cellcolor{chr(123)}([^{chr(123)}{chr(125)}]*){chr(125)}')")
W(f"RE_HLINE = re.compile(r'{BACKSLASH}{BACKSLASH}(hline|toprule|midrule|bottomrule)')")
W(f"RE_ROW_SPLIT = re.compile(r'{BACKSLASH}{BACKSLASH}{BACKSLASH}{BACKSLASH}')")
W(f"RE_HTML_TABLE = re.compile(r'<table[^>]*>(.*?)</table>', re.DOTALL | re.IGNORECASE)")
W(f"RE_HTML_TR = re.compile(r'<tr[^>]*>(.*?)</tr>', re.DOTALL | re.IGNORECASE)")
W(f"RE_HTML_CELL = re.compile(r'<(th|td)([^>]*)>(.*?)</(?:th|td)>', re.DOTALL | re.IGNORECASE)")
W(f"RE_ATTR = re.compile(r'(colspan|rowspan|style|class)={DQ}([^{DQ}]*){DQ}')")
W("")
W("")
W("class TableProcessor:")
W(f'    r"""Processor for converting tables to MDX format.')
W(f"")
W(f"    {ZWNJ.join(['پردازشگر', 'تبدیل'])} جداول به فرمت MDX.")
W(f'    """')
W("")
W("    def __init__(self, config: Optional[dict] = None) -> None:")
W('        r"""Initialize table processor."""')
W("        self.config = config or {}")
W('        self.caption_position: str = self.config.get("caption_position", "below")')
W('        self.default_rtl: bool = self.config.get("default_rtl", True)')
W("")
W("    def process(self, text: str, source_format: str = " + DQ + "latex" + DQ + ") -> str:")
W('        r"""Process table text and return MDX output.')
W("")
W("        Args:")
W("            text: Raw table source text.")
W('            source_format: "latex" or "html".')
W("")
W("        Returns:")
W("            MDX-compatible table string.")
W('        """')
W("        if source_format == " + DQ + "latex" + DQ + ":")
W("            model = self.parse_latex_table(text)")
W("        elif source_format == " + DQ + "html" + DQ + ":")
W("            model = self.parse_html_table(text)")
W("        else:")
W('            logger.warning("Unknown source format: %s", source_format)')
W("            return text")
W("")
W("        if model.is_simple:")
W("            return self.render_markdown_table(model)")
W("        return self.render_html_table(model)")
W("")

# -- parse_latex_table --
W("    def parse_latex_table(self, text: str) -> TableModel:")
W('        r"""Parse a LaTeX table environment into TableModel.')
W(f"")
W(f"        {ZWNJ.join(['تحلیل', 'جدول'])} LaTeX به مدل جدول.")
W('        """')
W("        env_type, col_spec_str, body = self._detect_latex_env(text)")
W("        if body is None:")
W('            return TableModel()')
W("")
W("        col_alignments = self._parse_col_spec(col_spec_str)")
W("        caption, label = self._extract_caption_label(text)")
W("        row_colors = self._detect_row_colors(text)")
W("        headers, rows, has_merged = self._parse_latex_rows(body, len(col_alignments))")
W("")
W("        return TableModel(")
W("            headers=headers,")
W("            rows=rows,")
W("            caption=caption,")
W("            label=label,")
W("            is_rtl=self.default_rtl,")
W('            is_long=(env_type == "longtable"),')
W('            is_landscape=(env_type == "sidewaystable"),')
W('            is_full_width=(env_type == "tabularx"),')
W("            has_colors=bool(row_colors),")
W("            has_merged_cells=has_merged,")
W("            col_alignments=col_alignments,")
W("            caption_position=self.caption_position,")
W("        )")
W("")

# -- _detect_latex_env --
W("    def _detect_latex_env(self, text: str) -> Tuple[str, str, Optional[str]]:")
W('        r"""Detect LaTeX table environment type and extract body."""')
W("        match = RE_LATEX_TABLE_ENV.search(text)")
W("        if not match:")
W('            return ("tabular", "", None)')
W("        env_type = match.group(1)")
W("        inner = match.group(2)")
W("        # Extract column spec (first {...} in inner)")
W("        spec_match = RE_COL_SPEC.search(inner)")
W('        col_spec = spec_match.group(1) if spec_match else ""')
W("        # Body is after column spec")
W("        if spec_match:")
W("            body = inner[spec_match.end():]")
W("        else:")
W("            body = inner")
W("        return (env_type, col_spec, body.strip())")
W("")

# -- _parse_col_spec --
W("    @staticmethod")
W("    def _parse_col_spec(spec: str) -> List[str]:")
W('        r"""Parse LaTeX column spec like |c|l|r| into alignment list."""')
W("        alignments: List[str] = []")
W("        for ch in spec:")
W("            if ch in ('l', 'c', 'r', 'X', 'p'):")
W("                if ch == 'l' or ch == 'X':")
W('                    alignments.append("left")')
W("                elif ch == 'r':")
W('                    alignments.append("right")')
W("                else:")
W('                    alignments.append("center")')
W("        return alignments")
W("")

# -- _extract_caption_label --
W("    @staticmethod")
W("    def _extract_caption_label(text: str) -> Tuple[Optional[str], Optional[str]]:")
W('        r"""Extract caption and label from LaTeX source."""')
W("        cap_match = RE_CAPTION.search(text)")
W("        label_match = RE_LABEL.search(text)")
W("        caption = cap_match.group(1).strip() if cap_match else None")
W("        label = label_match.group(1).strip() if label_match else None")
W("        return (caption, label)")
W("")

# -- _detect_row_colors --
W("    @staticmethod")
W("    def _detect_row_colors(text: str) -> Optional[dict]:")
W('        r"""Detect rowcolors command in LaTeX."""')
W("        match = RE_ROWCOLORS.search(text)")
W("        if match:")
W("            return {")
W('                "start": int(match.group(1)),')
W('                "odd_color": match.group(2),')
W('                "even_color": match.group(3),')
W("            }")
W("        return None")
W("")

# -- _parse_latex_rows --
W("    def _parse_latex_rows(")
W("        self, body: str, col_count: int")
W("    ) -> Tuple[List[List[TableCell]], List[List[TableCell]], bool]:")
W('        r"""Parse LaTeX table body into header and data rows."""')
W("        # Remove hline/toprule/midrule/bottomrule")
W("        cleaned = RE_HLINE.sub('', body)")
W("        raw_rows = RE_ROW_SPLIT.split(cleaned)")
W("        raw_rows = [r.strip() for r in raw_rows if r.strip()]")
W("")
W("        has_merged = False")
W("        parsed_rows: List[List[TableCell]] = []")
W("")
W("        for raw_row in raw_rows:")
W("            cells_text = raw_row.split('&')")
W("            row_cells: List[TableCell] = []")
W("            for ct in cells_text:")
W("                cell, merged = self._parse_latex_cell(ct.strip())")
W("                if merged:")
W("                    has_merged = True")
W("                row_cells.append(cell)")
W("            if row_cells:")
W("                parsed_rows.append(row_cells)")
W("")
W("        # First row is header if we have data")
W("        headers: List[List[TableCell]] = []")
W("        rows: List[List[TableCell]] = []")
W("        if parsed_rows:")
W("            header_row = parsed_rows[0]")
W("            for c in header_row:")
W("                c.is_header = True")
W("            headers = [header_row]")
W("            rows = parsed_rows[1:]")
W("")
W("        return (headers, rows, has_merged)")
W("")

# -- _parse_latex_cell --
W("    @staticmethod")
W("    def _parse_latex_cell(text: str) -> Tuple[TableCell, bool]:")
W('        r"""Parse a single LaTeX cell, detecting multicolumn/multirow."""')
W("        merged = False")
W("        colspan = 1")
W("        rowspan = 1")
W("        style: Optional[CellStyle] = None")
W("        content = text")
W("")
W("        # Check for multicolumn")
W("        mc_match = RE_MULTICOLUMN.search(content)")
W("        if mc_match:")
W("            colspan = int(mc_match.group(1))")
W("            content = mc_match.group(3)")
W("            merged = True")
W("")
W("        # Check for multirow")
W("        mr_match = RE_MULTIROW.search(content)")
W("        if mr_match:")
W("            rowspan = int(mr_match.group(1))")
W("            content = mr_match.group(3)")
W("            merged = True")
W("")
W("        # Check for cellcolor")
W("        cc_match = RE_CELLCOLOR.search(content)")
W("        if cc_match:")
W("            style = CellStyle(background_color=cc_match.group(1))")
W("            content = RE_CELLCOLOR.sub('', content)")
W("")
W("        content = content.strip()")
W("        return (")
W("            TableCell(")
W("                content=content,")
W("                colspan=colspan,")
W("                rowspan=rowspan,")
W("                style=style,")
W("            ),")
W("            merged,")
W("        )")
W("")

# -- parse_html_table --
W("    def parse_html_table(self, html: str) -> TableModel:")
W('        r"""Parse an HTML table into TableModel.')
W(f"")
W(f"        {ZWNJ.join(['تحلیل', 'جدول'])} HTML به مدل جدول.")
W('        """')
W("        table_match = RE_HTML_TABLE.search(html)")
W("        if not table_match:")
W("            return TableModel()")
W("")
W("        table_inner = table_match.group(1)")
W("        tr_matches = RE_HTML_TR.findall(table_inner)")
W("")
W("        headers: List[List[TableCell]] = []")
W("        rows: List[List[TableCell]] = []")
W("        has_merged = False")
W("        has_colors = False")
W("")
W("        for tr_html in tr_matches:")
W("            cell_matches = RE_HTML_CELL.findall(tr_html)")
W("            row_cells: List[TableCell] = []")
W("            is_header_row = False")
W("")
W("            for tag, attrs, content in cell_matches:")
W('                if tag.lower() == "th":')
W("                    is_header_row = True")
W("                cell, m, c = self._parse_html_cell(tag, attrs, content)")
W("                if m:")
W("                    has_merged = True")
W("                if c:")
W("                    has_colors = True")
W("                row_cells.append(cell)")
W("")
W("            if row_cells:")
W("                if is_header_row:")
W("                    for c in row_cells:")
W("                        c.is_header = True")
W("                    headers.append(row_cells)")
W("                else:")
W("                    rows.append(row_cells)")
W("")
W("        return TableModel(")
W("            headers=headers,")
W("            rows=rows,")
W("            is_rtl=self.default_rtl,")
W("            has_colors=has_colors,")
W("            has_merged_cells=has_merged,")
W("            caption_position=self.caption_position,")
W("        )")
W("")

# -- _parse_html_cell --
W("    @staticmethod")
W("    def _parse_html_cell(")
W("        tag: str, attrs: str, content: str")
W("    ) -> Tuple[TableCell, bool, bool]:")
W('        r"""Parse a single HTML cell element."""')
W("        colspan = 1")
W("        rowspan = 1")
W("        has_color = False")
W("        style: Optional[CellStyle] = None")
W("")
W("        attr_matches = RE_ATTR.findall(attrs)")
W("        for attr_name, attr_val in attr_matches:")
W('            if attr_name == "colspan":')
W("                colspan = int(attr_val)")
W('            elif attr_name == "rowspan":')
W("                rowspan = int(attr_val)")
W('            elif attr_name == "style":')
W('                style = CellStyle(css_class=attr_val)')
W('                if "background" in attr_val or "color" in attr_val:')
W("                    has_color = True")
W('            elif attr_name == "class":')
W("                style = style or CellStyle()")
W("                style.css_class = attr_val")
W("")
W("        merged = colspan > 1 or rowspan > 1")
W("        return (")
W("            TableCell(")
W("                content=content.strip(),")
W("                colspan=colspan,")
W("                rowspan=rowspan,")
W("                style=style,")
W('                is_header=(tag.lower() == "th"),')
W("            ),")
W("            merged,")
W("            has_color,")
W("        )")
W("")

# -- render_markdown_table --
W("    def render_markdown_table(self, model: TableModel) -> str:")
W('        r"""Render TableModel as Markdown pipe table.')
W(f"")
W(f"        رندر جدول به صورت Markdown {ZWNJ.join(['لوله', 'ای'])}.")
W('        """')
W("        out_lines: List[str] = []")
W("")
W("        # Caption above if configured")
W('        if model.caption and model.caption_position == "above":')
W('            out_lines.append("")')
W('            out_lines.append("**" + model.caption + "**")')
W('            out_lines.append("")')
W("")
W("        # Header row")
W("        if model.headers:")
W("            hdr = model.headers[0]")
W('            hdr_line = "| " + " | ".join(c.content for c in hdr) + " |"')
W("            out_lines.append(hdr_line)")
W("            # Separator with alignment")
W("            seps: List[str] = []")
W("            for i, c in enumerate(hdr):")
W("                align = model.col_alignments[i] if i < len(model.col_alignments) else " + DQ + "left" + DQ)
W('                if align == "center":')
W('                    seps.append(":---:")')
W('                elif align == "right":')
W('                    seps.append("---:")')
W("                else:")
W('                    seps.append("---")')
W('            out_lines.append("| " + " | ".join(seps) + " |")')
W("")
W("        # Data rows")
W("        for row in model.rows:")
W('            row_line = "| " + " | ".join(c.content for c in row) + " |"')
W("            out_lines.append(row_line)")
W("")
W("        # Caption below if configured")
W('        if model.caption and model.caption_position == "below":')
W('            out_lines.append("")')
W('            out_lines.append("**" + model.caption + "**")')
W("")
W('        return "\\n".join(out_lines)')
W("")

# -- render_html_table --
W("    def render_html_table(self, model: TableModel) -> str:")
W('        r"""Render TableModel as HTML table for MDX.')
W(f"")
W(f"        رندر جدول به صورت HTML برای MDX.")
W('        """')
W("        out_lines: List[str] = []")
W("        indent = " + DQ + "  " + DQ)
W("")
W("        # Wrapper for special types")
W("        wrapper_open, wrapper_close = self._get_wrapper(model)")
W("        if wrapper_open:")
W("            out_lines.append(wrapper_open)")
W("")
W("        # Table tag")
W('        rtl_style = " dir=" + chr(34) + "rtl" + chr(34) if model.is_rtl else ""')
W('        width_style = " style=" + chr(34) + "width:100%" + chr(34) if model.is_full_width else ""')
W('        label_id = " id=" + chr(34) + model.label + chr(34) if model.label else ""')
W('        out_lines.append("<table" + label_id + rtl_style + width_style + ">")')
W("")
W("        # Caption above")
W('        if model.caption and model.caption_position == "above":')
W('            out_lines.append(indent + "<caption>" + model.caption + "</caption>")')
W("")
W("        # Header")
W("        if model.headers:")
W('            out_lines.append(indent + "<thead>")')
W("            for hdr_row in model.headers:")
W("                out_lines.append(self._render_html_row(hdr_row, indent + indent))")
W('            out_lines.append(indent + "</thead>")')
W("")
W("        # Body")
W("        if model.rows:")
W('            out_lines.append(indent + "<tbody>")')
W("            for row in model.rows:")
W("                out_lines.append(self._render_html_row(row, indent + indent))")
W('            out_lines.append(indent + "</tbody>")')
W("")
W("        # Caption below")
W('        if model.caption and model.caption_position == "below":')
W('            out_lines.append(indent + "<caption style=" + chr(34) + "caption-side:bottom" + chr(34) + ">" + model.caption + "</caption>")')
W("")
W('        out_lines.append("</table>")')
W("")
W("        if wrapper_close:")
W("            out_lines.append(wrapper_close)")
W("")
W('        return "\\n".join(out_lines)')
W("")

# -- _get_wrapper --
W("    @staticmethod")
W("    def _get_wrapper(model: TableModel) -> Tuple[Optional[str], Optional[str]]:")
W('        r"""Get wrapper div for special table types."""')
W("        if model.is_long:")
W("            return (")
W('                ' + repr('<div style="overflow-x:auto">') + ',')
W('                "</div>",')
W("            )")
W("        if model.is_landscape:")
W("            return (")
W('                ' + repr('<div className="landscape-table">') + ',')
W('                "</div>",')
W("            )")
W("        return (None, None)")
W("")

# -- _render_html_row --
W("    @staticmethod")
W("    def _render_html_row(cells: List[TableCell], indent: str) -> str:")
W('        r"""Render a single HTML table row."""')
W('        parts: List[str] = [indent + "<tr>"]')
W("        for cell in cells:")
W('            tag = "th" if cell.is_header else "td"')
W("            attrs = " + DQ + DQ)
W("            if cell.colspan > 1:")
W("""            attrs += ' colspan="' + str(cell.colspan) + '"'""")
W("            if cell.rowspan > 1:")
W("""            attrs += ' rowspan="' + str(cell.rowspan) + '"'""")
W("            if cell.style and cell.style.background_color:")
W("""            attrs += ' style="background-color:' + cell.style.background_color + '"'""")
W('            parts.append(indent + "  <" + tag + attrs + ">" + cell.content + "</" + tag + ">")')
W('        parts.append(indent + "</tr>")')
W("        return " + DQ + chr(92) + "n" + DQ + ".join(parts)")


# Write the file
content = NL.join(lines) + NL
os.makedirs("formatforge/core/processors", exist_ok=True)
with open("formatforge/core/processors/table_processor.py", "w", encoding="utf-8-sig") as f:
    f.write(content)
print(f"table_processor.py written: {len(lines)} lines")
