# -*- coding: utf-8 -*-
"""
Writer script: creates tests/test_admonition_processor.py
and updates __init__.py
Run: python _write_admonition_tests.py
"""
import os
import ast

BACKSLASH = chr(92)
ZWNJ = chr(0x200C)
DQ = chr(34)
SQ = chr(39)
NL = "\n"
LBRACE = chr(123)
RBRACE = chr(125)

lines = []

def W(line=""):
    lines.append(line)


# ═══════════════════════════════════════════
# Header
# ═══════════════════════════════════════════
W("# -*- coding: utf-8-sig -*-")
W('r"""Tests for admonition_processor module.')
W("")
W("Test suite for FormatForge admonition processing.")
W('"""')
W("import pytest")
W("")
W("from formatforge.core.processors.admonition_models import (")
W("    AdmonitionRef,")
W("    AdmonitionKind,")
W("    AdmonitionSource,")
W("    ENVIRONMENT_MAP,")
W("    MD_CALLOUT_MAP,")
W("    RST_DIRECTIVE_MAP,")
W("    HTML_CLASS_MAP,")
W(")")
W("from formatforge.core.processors.admonition_processor import AdmonitionProcessor")
W("")
W("")
W("ZWNJ = chr(0x200C)")
W("BS = chr(92)")
W("LBRACE = chr(123)")
W("RBRACE = chr(125)")
W("")
W("")

# ═══════════════════════════════════════════
# Fixtures
# ═══════════════════════════════════════════
W("@pytest.fixture")
W("def processor() -> AdmonitionProcessor:")
W('    r"""Create a default AdmonitionProcessor instance."""')
W("    return AdmonitionProcessor()")
W("")
W("")

# ═══════════════════════════════════════════
# Test 1: LaTeX environments
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 1: LaTeX theorem/definition/proof environments")
W("# " + "=" * 60)
W("")
W("")
W("class TestLatexEnvironments:")
W('    r"""Tests for LaTeX environment detection."""')
W("")

# theorem with title
W("    def test_theorem_with_title(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing theorem environment with optional title."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'theorem' + RBRACE + '[Pythagorean]'")
W("            + chr(10)")
W("            + 'a^2 + b^2 = c^2'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'theorem' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.THEOREM")
W("        assert refs[0].title == 'Pythagorean'")
W("        assert 'a^2' in refs[0].body")
W("        assert refs[0].component == 'Theorem'")
W("")

# theorem without title
W("    def test_theorem_without_title(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing theorem without optional title."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'theorem' + RBRACE")
W("            + chr(10)")
W("            + 'Some statement.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'theorem' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].title is None")
W("        assert 'Some statement.' in refs[0].body")
W("")

# definition
W("    def test_definition_env(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing definition environment."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'definition' + RBRACE + '[Group]'")
W("            + chr(10)")
W("            + 'A group is a set with an operation.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'definition' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.DEFINITION")
W("        assert refs[0].component == 'Definition'")
W("        assert refs[0].title == 'Group'")
W("")

# proof
W("    def test_proof_env(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing proof environment."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'proof' + RBRACE")
W("            + chr(10)")
W("            + 'This follows from axiom 1.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'proof' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.PROOF")
W("        assert refs[0].component == 'Proof'")
W("")

# lemma
W("    def test_lemma_env(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing lemma environment."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'lemma' + RBRACE")
W("            + chr(10)")
W("            + 'A useful lemma.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'lemma' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.LEMMA")
W("        assert refs[0].component == 'Theorem'")
W("        assert refs[0].props.get('type') == 'lemma'")
W("")

# with label
W("    def test_env_with_label(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing environment with label."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'theorem' + RBRACE + '[Main]'")
W("            + chr(10)")
W("            + BS + 'label' + LBRACE + 'thm:main' + RBRACE")
W("            + chr(10)")
W("            + 'The main theorem.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'theorem' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].label == 'thm:main'")
W("        assert refs[0].title == 'Main'")
W("        assert 'thm:main' not in refs[0].body")
W("")

# example
W("    def test_example_env(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing example environment."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'example' + RBRACE")
W("            + chr(10)")
W("            + 'Consider x=1.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'example' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.EXAMPLE")
W("        assert refs[0].component == 'Example'")
W("")

# remark
W("    def test_remark_env(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing remark environment."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'remark' + RBRACE")
W("            + chr(10)")
W("            + 'Note this fact.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'remark' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.REMARK")
W("        assert refs[0].component == 'Admonition'")
W("")

# multiple envs
W("    def test_multiple_envs(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test finding multiple environments in one text."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'theorem' + RBRACE")
W("            + chr(10) + 'T1' + chr(10)")
W("            + BS + 'end' + LBRACE + 'theorem' + RBRACE")
W("            + chr(10)")
W("            + BS + 'begin' + LBRACE + 'proof' + RBRACE")
W("            + chr(10) + 'P1' + chr(10)")
W("            + BS + 'end' + LBRACE + 'proof' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 2")
W("        assert refs[0].kind == AdmonitionKind.THEOREM")
W("        assert refs[1].kind == AdmonitionKind.PROOF")
W("")
W("")

# ═══════════════════════════════════════════
# Test 2: tcolorbox
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 2: tcolorbox")
W("# " + "=" * 60)
W("")
W("")
W("class TestTcolorbox:")
W('    r"""Tests for tcolorbox detection."""')
W("")

W("    def test_tcolorbox_with_title(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing tcolorbox with title option."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'tcolorbox' + RBRACE + '[title=Important Note]'")
W("            + chr(10)")
W("            + 'Some important content.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'tcolorbox' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].title == 'Important Note'")
W("        assert refs[0].source == AdmonitionSource.LATEX_TCOLORBOX")
W("")

W("    def test_tcolorbox_red_is_danger(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test that red tcolorbox maps to danger."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'tcolorbox' + RBRACE + '[colback=red!10]'")
W("            + chr(10)")
W("            + 'Danger zone.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'tcolorbox' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.DANGER")
W("")

W("    def test_tcolorbox_no_options(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test tcolorbox without options."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'tcolorbox' + RBRACE")
W("            + chr(10)")
W("            + 'Plain box.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'tcolorbox' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.NOTE  # default")
W("")

W("    def test_tcolorbox_with_label(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test tcolorbox with label in body."""')
W("        text = (")
W("            BS + 'begin' + LBRACE + 'tcolorbox' + RBRACE + '[title=Tip]'")
W("            + chr(10)")
W("            + BS + 'label' + LBRACE + 'box:tip1' + RBRACE")
W("            + chr(10)")
W("            + 'A useful tip.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'tcolorbox' + RBRACE")
W("        )")
W("        refs = processor.find_admonitions(text, 'latex')")
W("        assert len(refs) == 1")
W("        assert refs[0].label == 'box:tip1'")
W("        assert 'box:tip1' not in refs[0].body")
W("")
W("")

# ═══════════════════════════════════════════
# Test 3: Markdown callouts
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 3: Markdown callouts")
W("# " + "=" * 60)
W("")
W("")
W("class TestMarkdownCallouts:")
W('    r"""Tests for Markdown callout detection."""')
W("")

W("    def test_note_callout(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing > [!NOTE] callout."""')
W("        text = (")
W("            '> [!NOTE]' + chr(10)")
W("            + '> This is a note.' + chr(10)")
W("            + '> Second line.'")
W("        )")
W("        refs = processor.find_admonitions(text, 'markdown')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.NOTE")
W("        assert 'This is a note.' in refs[0].body")
W("        assert 'Second line.' in refs[0].body")
W("")

W("    def test_warning_callout(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing > [!WARNING] callout."""')
W("        text = (")
W("            '> [!WARNING] Be careful' + chr(10)")
W("            + '> Something dangerous.'")
W("        )")
W("        refs = processor.find_admonitions(text, 'markdown')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.WARNING")
W("        assert refs[0].title == 'Be careful'")
W("")

W("    def test_tip_callout(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing > [!TIP] callout."""')
W("        text = (")
W("            '> [!TIP]' + chr(10)")
W("            + '> A handy tip.'")
W("        )")
W("        refs = processor.find_admonitions(text, 'markdown')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.TIP")
W("")

W("    def test_callout_no_body(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test callout with only header, no body lines."""')
W("        text = '> [!INFO] Just a header'")
W("        refs = processor.find_admonitions(text, 'markdown')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.INFO")
W("        assert refs[0].title == 'Just a header'")
W("")
W("")

# ═══════════════════════════════════════════
# Test 4: HTML boxes
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 4: HTML admonition boxes")
W("# " + "=" * 60)
W("")
W("")
W("class TestHTMLBoxes:")
W('    r"""Tests for HTML admonition box detection."""')
W("")

W("    def test_note_div(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing <div class="note">."""')
W("        text = '<div class=' + chr(34) + 'note' + chr(34) + '>Note content here.</div>'")
W("        refs = processor.find_admonitions(text, 'html')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.NOTE")
W("        assert 'Note content here.' in refs[0].body")
W("")

W("    def test_warning_div(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing <div class="warning">."""')
W("        text = '<div class=' + chr(34) + 'warning' + chr(34) + '>Watch out!</div>'")
W("        refs = processor.find_admonitions(text, 'html')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.WARNING")
W("")

W("    def test_unknown_class_defaults_note(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test that unknown class defaults to NOTE."""')
W("        text = '<div class=' + chr(34) + 'custom-box' + chr(34) + '>Content.</div>'")
W("        refs = processor.find_admonitions(text, 'html')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.NOTE")
W("")
W("")

# ═══════════════════════════════════════════
# Test 5: HTML details/summary
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 5: HTML details/summary")
W("# " + "=" * 60)
W("")
W("")
W("class TestHTMLDetails:")
W('    r"""Tests for HTML details/summary detection."""')
W("")

W("    def test_details_with_summary(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing <details><summary>."""')
W("        text = '<details><summary>Click me</summary>Hidden content.</details>'")
W("        refs = processor.find_admonitions(text, 'html')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.DETAILS")
W("        assert refs[0].title == 'Click me'")
W("        assert 'Hidden content.' in refs[0].body")
W("        assert refs[0].component == 'Details'")
W("")

W("    def test_details_without_summary(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing <details> without <summary>."""')
W("        text = '<details>Just content.</details>'")
W("        refs = processor.find_admonitions(text, 'html')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.DETAILS")
W("        assert refs[0].title is None")
W("")
W("")

# ═══════════════════════════════════════════
# Test 6: RST directives
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 6: RST directives")
W("# " + "=" * 60)
W("")
W("")
W("class TestRSTDirectives:")
W('    r"""Tests for RST admonition directive detection."""')
W("")

W("    def test_note_directive(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing .. note:: directive."""')
W("        text = (")
W("            '.. note:: Important' + chr(10)")
W("            + '   This is the body.' + chr(10)")
W("            + '   Second line.'")
W("        )")
W("        refs = processor.find_admonitions(text, 'rst')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.NOTE")
W("        assert refs[0].title == 'Important'")
W("        assert 'This is the body.' in refs[0].body")
W("        assert 'Second line.' in refs[0].body")
W("")

W("    def test_warning_directive(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing .. warning:: directive."""')
W("        text = (")
W("            '.. warning::' + chr(10)")
W("            + '   Be careful here.'")
W("        )")
W("        refs = processor.find_admonitions(text, 'rst')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.WARNING")
W("")

W("    def test_tip_directive(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test parsing .. tip:: directive."""')
W("        text = (")
W("            '.. tip::' + chr(10)")
W("            + '   A helpful tip.'")
W("        )")
W("        refs = processor.find_admonitions(text, 'rst')")
W("        assert len(refs) == 1")
W("        assert refs[0].kind == AdmonitionKind.TIP")
W("")
W("")

# ═══════════════════════════════════════════
# Test 7: MDX rendering
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 7: MDX rendering")
W("# " + "=" * 60)
W("")
W("")
W("class TestMDXRendering:")
W('    r"""Tests for MDX component rendering."""')
W("")

W("    def test_render_theorem(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test rendering theorem as MDX component."""')
W("        ref = AdmonitionRef(")
W("            kind=AdmonitionKind.THEOREM,")
W("            title='Pythagorean',")
W("            body='a^2 + b^2 = c^2',")
W("            component='Theorem',")
W("            props={'type': 'theorem'},")
W("            label='thm:pyth',")
W("        )")
W("        result = processor.render_mdx(ref)")
W("        assert '<Theorem' in result")
W("        assert 'Pythagorean' in result")
W("        assert 'thm:pyth' in result")
W("        assert 'a^2 + b^2 = c^2' in result")
W("        assert '</Theorem>' in result")
W("")

W("    def test_render_admonition_note(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test rendering note admonition."""')
W("        ref = AdmonitionRef(")
W("            kind=AdmonitionKind.NOTE,")
W("            body='Remember this.',")
W("            component='Admonition',")
W("            props={'type': 'note'},")
W("        )")
W("        result = processor.render_mdx(ref)")
W("        assert '<Admonition' in result")
W("        assert 'type=' in result")
W("        assert 'note' in result")
W("        assert 'Remember this.' in result")
W("        assert '</Admonition>' in result")
W("")

W("    def test_render_details(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test rendering details component."""')
W("        ref = AdmonitionRef(")
W("            kind=AdmonitionKind.DETAILS,")
W("            title='Click to expand',")
W("            body='Hidden info.',")
W("            component='Details',")
W("        )")
W("        result = processor.render_mdx(ref)")
W("        assert '<Details' in result")
W("        assert 'Click to expand' in result")
W("        assert 'Hidden info.' in result")
W("        assert '</Details>' in result")
W("")

W("    def test_render_without_title(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test rendering without title."""')
W("        ref = AdmonitionRef(")
W("            body='Just body.',")
W("            component='Admonition',")
W("            props={'type': 'note'},")
W("        )")
W("        result = processor.render_mdx(ref)")
W("        assert '<Admonition' in result")
W("        assert 'title=' not in result")
W("")

W("    def test_render_empty_body(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test rendering with empty body."""')
W("        ref = AdmonitionRef(")
W("            component='Admonition',")
W("            props={'type': 'warning'},")
W("        )")
W("        result = processor.render_mdx(ref)")
W("        assert '<Admonition' in result")
W("        assert '</Admonition>' in result")
W("")
W("")

# ═══════════════════════════════════════════
# Test 8: Full process (e2e)
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 8: Full text processing (e2e)")
W("# " + "=" * 60)
W("")
W("")
W("class TestFullProcess:")
W('    r"""End-to-end tests for admonition processing."""')
W("")

W("    def test_process_latex(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test full process on LaTeX theorem."""')
W("        text = (")
W("            'Before text.' + chr(10)")
W("            + BS + 'begin' + LBRACE + 'theorem' + RBRACE + '[Cool]'")
W("            + chr(10)")
W("            + 'Statement here.'")
W("            + chr(10)")
W("            + BS + 'end' + LBRACE + 'theorem' + RBRACE")
W("            + chr(10)")
W("            + 'After text.'")
W("        )")
W("        result = processor.process(text, 'latex')")
W("        assert '<Theorem' in result")
W("        assert 'Before text.' in result")
W("        assert 'After text.' in result")
W("        assert 'Statement here.' in result")
W("")

W("    def test_process_markdown(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test full process on Markdown callout."""')
W("        text = (")
W("            'Before.' + chr(10)")
W("            + '> [!WARNING] Watch out' + chr(10)")
W("            + '> Be careful.' + chr(10)")
W("            + 'After.'")
W("        )")
W("        result = processor.process(text, 'markdown')")
W("        assert '<Admonition' in result")
W("        assert 'warning' in result")
W("")

W("    def test_process_html(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test full process on HTML box."""')
W("        text = '<p>Before</p><div class=' + chr(34) + 'note' + chr(34) + '>Note body.</div><p>After</p>'")
W("        result = processor.process(text, 'html')")
W("        assert '<Admonition' in result")
W("        assert 'Note body.' in result")
W("")

W("    def test_process_preserves_unrelated(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test that non-admonition text is preserved."""')
W("        text = 'Just regular text, no admonitions.'")
W("        result = processor.process(text, 'latex')")
W("        assert result == text")
W("")
W("")

# ═══════════════════════════════════════════
# Test 9: Persian content
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 9: Persian content in admonitions")
W("# " + "=" * 60)
W("")
W("")
W("class TestPersianAdmonitions:")
W('    r"""Tests for Persian content in admonitions."""')
W("")

W("    def test_persian_theorem_title(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test Persian title in theorem."""')
W("        ref = AdmonitionRef(")
W("            kind=AdmonitionKind.THEOREM,")
W("            title=" + repr("قضیه فیثاغورس") + ",")
W("            body='a^2 + b^2 = c^2',")
W("            component='Theorem',")
W("            props={'type': 'theorem'},")
W("        )")
W("        result = processor.render_mdx(ref)")
W("        assert " + repr("قضیه فیثاغورس") + " in result")
W("")

W("    def test_persian_body(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test Persian body text."""')
W("        ref = AdmonitionRef(")
W("            body=" + repr("این یک نکته مهم است.") + ",")
W("            component='Admonition',")
W("            props={'type': 'note'},")
W("        )")
W("        result = processor.render_mdx(ref)")
W("        assert " + repr("این یک نکته مهم است.") + " in result")
W("")

W("    def test_persian_zwnj_preserved(self, processor: AdmonitionProcessor) -> None:")
W('        r"""Test ZWNJ preservation in admonition."""')
W("        body = " + repr("کتاب") + " + ZWNJ + " + repr("خانه"))
W("        ref = AdmonitionRef(")
W("            body=body,")
W("            component='Admonition',")
W("            props={'type': 'note'},")
W("        )")
W("        result = processor.render_mdx(ref)")
W("        assert ZWNJ in result")
W("        assert " + repr("کتاب") + " in result")
W("        assert " + repr("خانه") + " in result")
W("")
W("")

# ═══════════════════════════════════════════
# Test 10: Model and map tests
# ═══════════════════════════════════════════
W("# " + "=" * 60)
W("# Test 10: Models and mappings")
W("# " + "=" * 60)
W("")
W("")
W("class TestModelsAndMaps:")
W('    r"""Tests for data models and mapping dictionaries."""')
W("")

W("    def test_environment_map_completeness(self) -> None:")
W('        r"""Test that ENVIRONMENT_MAP has expected keys."""')
W("        for env in ['theorem', 'lemma', 'definition', 'proof', 'example', 'remark']:")
W("            assert env in ENVIRONMENT_MAP")
W("")

W("    def test_md_callout_map_completeness(self) -> None:")
W('        r"""Test that MD_CALLOUT_MAP has expected keys."""')
W("        for key in ['NOTE', 'WARNING', 'TIP', 'DANGER', 'CAUTION']:")
W("            assert key in MD_CALLOUT_MAP")
W("")

W("    def test_rst_directive_map_completeness(self) -> None:")
W('        r"""Test that RST_DIRECTIVE_MAP has expected keys."""')
W("        for key in ['note', 'tip', 'warning', 'danger', 'caution']:")
W("            assert key in RST_DIRECTIVE_MAP")
W("")

W("    def test_html_class_map_completeness(self) -> None:")
W('        r"""Test that HTML_CLASS_MAP has expected keys."""')
W("        for key in ['note', 'warning', 'danger', 'tip']:")
W("            assert key in HTML_CLASS_MAP")
W("")

W("    def test_admonition_ref_defaults(self) -> None:")
W('        r"""Test AdmonitionRef default values."""')
W("        ref = AdmonitionRef()")
W("        assert ref.kind == AdmonitionKind.NOTE")
W("        assert ref.title is None")
W("        assert ref.body == ''")
W("        assert ref.component == 'Admonition'")
W("        assert ref.label is None")
W("")


# ═══════════════════════════════════════════
# Write file
# ═══════════════════════════════════════════
content = NL.join(lines) + NL

os.makedirs("tests", exist_ok=True)
filepath = os.path.join("tests", "test_admonition_processor.py")
with open(filepath, "w", encoding="utf-8-sig") as f:
    f.write(content)

print(f"Written: {filepath} ({len(lines)} lines)")

try:
    ast.parse(open(filepath, encoding="utf-8-sig").read())
    print("  Syntax: OK")
except SyntaxError as e:
    print(f"  Syntax ERROR line {e.lineno}: {e.msg}")


# ═══════════════════════════════════════════
# Update __init__.py
# ═══════════════════════════════════════════
init_path = os.path.join("formatforge", "core", "processors", "__init__.py")
with open(init_path, "r", encoding="utf-8-sig") as f:
    init_content = f.read()

if "AdmonitionProcessor" not in init_content:
    append_lines = [
        "",
        "from .admonition_processor import AdmonitionProcessor  # noqa: F401",
        "from .admonition_models import (  # noqa: F401",
        "    AdmonitionRef,",
        "    AdmonitionKind,",
        "    AdmonitionSource,",
        "    ENVIRONMENT_MAP,",
        "    MD_CALLOUT_MAP,",
        "    RST_DIRECTIVE_MAP,",
        "    HTML_CLASS_MAP,",
        ")",
        "",
    ]
    with open(init_path, "a", encoding="utf-8-sig") as f:
        f.write(NL.join(append_lines))
    print(f"Updated: {init_path} (appended admonition imports)")
else:
    print(f"Skipped: {init_path} (already has AdmonitionProcessor)")

print("\nDone! Run: pytest tests/test_admonition_processor.py -v")